# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  indexing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install IJ
        run: sudo snap install intellij-idea-community --channel=2023.3/stable --classic
      - name: IJ install Shared Indexes plugin
        run: intellij-idea-community installPlugins intellij.indexing.shared

      - name: IJ build shared indexes
        run: |
          mkdir results
          intellij-idea-community dump-shared-index project --project-id=multi-jar --project-dir=examples/multi-jar --output=results

      - name: IJ check indexes
        run: ls -lh results

      - name: Archive index artifacts
        uses: actions/upload-artifact@v3
        with:
          name: index-assets
          path: results
          if-no-files-found: error

  release:
    needs: indexing
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: index-assets
          path: indexing-results

      - name:
        run: ls -lr indexing-results

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.0
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset - metadata.json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: indexing-results/*.metadata.json
          asset_name: index.metadata.json
          asset_content_type: application/json

      - name: Upload Release Asset - index archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: indexing-results/*.ijx.xz
          asset_name: index.ijx.xz
          asset_content_type: application/zip

      - name: Upload Release Asset - sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: indexing-results/*.sha256
          asset_name: index.ijx.xz
          asset_content_type: text/plain
